paddingZero:
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=0 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=1 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=2 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=3 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=4 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=5 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=6 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=7 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=8 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=9 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=10 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=11 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=12 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=13 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=14 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=15 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=16 -DPADDING=0
	./FShare
	
paddingOne:
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=0 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=1 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=2 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=3 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=4 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=5 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=6 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=7 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=8 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=9 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=10 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=11 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=12 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=13 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=14 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=15 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=16 -DPADDING=1
	./FShare
	
all:
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=0 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=1 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=2 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=3 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=4 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=5 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=6 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=7 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=8 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=9 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=10 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=11 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=12 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=13 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=14 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=15 -DPADDING=0
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=16 -DPADDING=0
	./FShare
		g++ newFShare.cpp -o FShare -fopenmp -DNUM=0 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=1 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=2 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=3 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=4 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=5 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=6 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=7 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=8 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=9 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=10 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=11 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=12 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=13 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=14 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=15 -DPADDING=1
	./FShare
	g++ newFShare.cpp -o FShare -fopenmp -DNUM=16 -DPADDING=1
	./FShare

clean:
	rm -f data.csv